services:
  postgres:
    image: postgres:18
    container_name: educationSystem-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: educationSystem_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
